FROM node:20

WORKDIR /app

COPY package*.json ./

RUN yarn install
RUN npm install -g serve

COPY public ./public
COPY src ./src
COPY .env ./

RUN yarn build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
